import Head from 'next/head'
import { VStack } from '@chakra-ui/react'
import Tour from '../components/cards'

export default function Home() {
  return (
    <VStack>
      <Head>
        <title>Recommended Tour</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Tour />
    </VStack>


  )
}
